name: chess_master_3d
publish_to: "none"
description: Chess Master 3D - mobile & desktop chess with 3D/2D boards and AI.
version: 0.1.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  windows:

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  chess: ^0.8.1
  provider: ^6.1.2
  collection: ^1.18.0
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8

  # Optional neural model integration (Android/iOS). Desktop will fallback to Stockfish.
  # You can later enable a suitable plugin for TorchScript if desired.
  # Placeholder to keep structure clear.

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/config/
    - assets/sounds/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
